//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LooneyTunesDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class loonytune
    {
        public int id { get; set; }
        [Required(ErrorMessage ="Name is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Bio is Required")]
        public string Bio { get; set; }
        [Required(ErrorMessage ="First Appearance is Required")]
        public string Fappearance { get; set; }
        [Required(ErrorMessage ="Species is Required")]
        public string Species { get; set; }
        public int Clike { get; set; }
        public int Cdislike { get; set; }
        public string Picture { get; set; }
    }
}
